name: flutter_currency_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
